import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./components/Header/Header";

const Almendra = localFont({
  src: "./fonts/Almendra-Regular.ttf",
  weight: "100 700 900",
});

export const metadata: Metadata = {
  title: "Treasure Trove Game",
  description: "RPG generated by Evgeniy Berezkin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Almendra.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
